apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  targetNamespace: traefik
  valuesContent: |-
    globalArguments: {}
    ingressRoute:
      dashboard:
        enabled: true
    logs:
      general:
        level: DEBUG
